### ISSUE TITLE
This is just a +1. No issue.

### ISSUE THREAD

**Issue by chantastic** [JedWatson/list-to-array#1]
I swear, I was just thinking about this yesterday. Ruby has this great way of working with string lists that I love:

`%W(one two three)` => `["one", "two", "three"]`

**Comment by JedWatson** [comment]
haha :grinning:

**Comment by JedWatson** [comment]
The name of this package is actually a little nod to my Coldfusion history, which had a `listToArray` function that does basically the same thing.

**Comment by chantastic** [comment]
whoa! Coldfusion? you must be right at home with React ;)
